[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI", "Agent", "Ollama", "Model", "Provider"]
license = ["Apache-2.0"]
icon="icon.png"
name = "ai.ollama"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.ollama"
version = "1.1.1"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.ollama-native"
version = "1.1.1"
path = "../native/build/libs/ai.ollama-native-1.1.1.jar"
